### ISSUE TITLE
importlib.metadata.PackageNotFoundError

### ISSUE THREAD

**Issue by tranhoangnguyen03** [gorilla-llm/gorilla-cli#10]
```
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Scripts\gorilla-script.py", line 33, in <module>
    sys.exit(load_entry_point('gorilla-cli', 'console_scripts', 'gorilla')())
  File "C:\Users\Admin\anaconda3\Scripts\gorilla-script.py", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "C:\Users\Admin\anaconda3\lib\importlib\metadata\__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Users\Admin\anaconda3\lib\importlib\metadata\__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gorilla-cli
```

**Comment by ShishirPatil** [comment]
Hey @tranhoangnguyen03 Thank you for trying out Gorilla-cli. Can you tell me what command, and what OS, you used that led to this error so I can try to re-create the bug to solve?

Thanks!

**Comment by ShishirPatil** [comment]
Closing this. Feel free to re-open!
