### ISSUE TITLE
user id is missing

### ISSUE THREAD

**Issue by A-Sm1th** [gorilla-llm/gorilla-cli#13]
`
gorilla I want to list all files in the current directory
Traceback (most recent call last):
  File "/opt/homebrew/bin/gorilla", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/go_cli.py", line 128, in main
    user_id = get_user_id()
              ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/go_cli.py", line 76, in get_user_id
    assert user_id != ""
           ^^^^^^^^^^^^^
AssertionError
`

Which user id should I write before using Gorilla CLI ?

**Comment by ShishirPatil** [comment]
Hey @A-Sm1th  thank's for your interest in gorilla-cli 🦍 
Do you have `git` installed and configured? If not, here's how you can do it - 

If you are using Linux based system:
```
sudo apt install git     # <brew install git> if you are on macos
git config --global user.email 'your@email.com'.   # set-up your email 
```

And then re-install gorilla-cli:
```
rm ~/.gorilla-cli-* && pip uninstall gorilla-cli
pip install gorilla-cli
```

Let me know if you run into any issues!

**Comment by A-Sm1th** [comment]
It worked - thank you very much 🙌🏻
