### ISSUE TITLE
Executing cmd will result in encoding error utf-8

### ISSUE THREAD

**Issue by xxx1099836595** [gorilla-llm/gorilla-cli#32]
Traceback (most recent call last):
  File "D:\Conda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Conda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Conda\Scripts\gorilla.exe\__main__.py", line 7, in <module>
  File "D:\Conda\lib\site-packages\go_cli.py", line 158, in main
    exit_condition = execute_command(selected_command)
  File "D:\Conda\lib\site-packages\go_cli.py", line 123, in execute_command
    error_msg = process.stderr.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0
![企业微信截图_20230816090914](https://github.com/gorilla-llm/gorilla-cli/assets/56339543/956171e0-5b55-42ec-a6dc-7563793493ac)
xb2 in position 6: invalid start byte

**Comment by xxx1099836595** [comment]
We have found a problem. It should be that the generated command cannot be used in the Linux and Windows environment, and an exception will be thrown
