### ISSUE TITLE
python3.11 support

### ISSUE THREAD

**Issue by wmichelin** [gorilla-llm/gorilla-cli#4]
```
> python --version
Python 3.11.3
```

```
> gorilla help
Traceback (most recent call last):
  File "/opt/homebrew/bin/gorilla", line 5, in <module>
    from go_cli import main
  File "/opt/homebrew/lib/python3.11/site-packages/go_cli.py", line 24, in <module>
    import go_questionary
  File "/opt/homebrew/lib/python3.11/site-packages/go_questionary/__init__.py", line 2, in <module>
    from prompt_toolkit.validation import Validator, ValidationError
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/opt/homebrew/lib/python3.11/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py)
```

**Comment by ShishirPatil** [comment]
Thanks for the pointer @wmichelin Would you be interested in potentially helping us with a PR? Happy to merge and welcome you as a contributor!

**Comment by mohidmeer** [comment]
@ShishirPatil 
### I am using python 3.11.4 it seems fine 
![image](https://github.com/gorilla-llm/gorilla-cli/assets/48846069/eb4cfee7-59ef-43a1-b5a6-2491ab6a497a)

**Comment by abitrolly** [comment]
@wmichelin can this be closed?
