### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by adrianstaniec** [gorilla-llm/gorilla-cli#8]
I get this error message when trying to install with pip
```
Collecting gorilla-cli
  Downloading gorilla-cli-0.0.8.tar.gz (27 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Temp\pip-install-snfk72nj\gorilla-cli_57007838e78a490fb36390faa9c4a90c\setup.py", line 24, in <module>
          long_description=open("README.md").read(),
        File "C:\Users\adrian\scoop\apps\python\current\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1245: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Mindstormer619** [comment]
Same issue for me. Is this a Windows-specific thing maybe?

**Comment by ShishirPatil** [comment]
Ah thanks for raising this @adrianstaniec and @Mindstormer619. I'll fix this in the next release. 

Potential fix - in setup.py replace `long_description=open("README.md").read()` with `long_description=open("README.md", "r", encoding="utf-8").read()` and then install from source: 

```
git clone https://github.com/gorilla-llm/gorilla-cli.git 
cd gorilla-cli
pip install -e .
```

Just to make sure I can test it before tearing a new release, what OS and python version are you running on?

**Comment by Mindstormer619** [comment]
OS: Windows 10 22H2
Python: Python 3.11.4

**Comment by adrianstaniec** [comment]
OS: Windows 10 22H2

Windows 10 22H2
Python 3.10.8

**Comment by ShishirPatil** [comment]
Thank you! Did the above fix help at all? 👀
